image: Visual Studio 2017

branches:
  only:
    - master
    - develop
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/
skip_commits:
  files:
    - docs/*

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable --version 4.0.0

assembly_info:
  patch: false

before_build:
  - nuget restore source/Jobbr.Server.sln
  - ps: C:\ProgramData\chocolatey\lib\GitVersion.Portable\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo

platform: Any CPU
configuration: Release

build:
  parallel: true 
  project: source/Jobbr.Server.sln

after_build:
  - cmd: nuget install ILMerge -ExcludeVersion -Version 2.14.1208
  - cmd: mkdir ilmerged
  - cmd: mkdir ilmerged/net462
  - cmd: ILMerge\tools\ILMerge.exe /out:ilmerged/net462/Jobbr.Server.dll source/Jobbr.Server/bin/Release/net462/Jobbr.Server.dll source/Jobbr.Server/bin/Release/net462/AutoMapper.dll source/Jobbr.Server/bin/Release/net462/NCrontab.dll source/Jobbr.Server/bin/Release/net462/Newtonsoft.Json.dll source/Jobbr.Server/bin/Release/net462/Ninject.dll /target:library /targetplatform:v4,C:\Windows\Microsoft.NET\Framework64\v4.0.30319 /wildcards /internalize:internalize_exclude.txt /allowDup:HttpRequestMessageExtensions /allowDup:MediaTypeFormatterExtensions
  - cmd: mkdir ilmerged/netstandard2.0
  - cmd: ILMerge\tools\ILMerge.exe /out:ilmerged/netstandard2.0/Jobbr.Server.dll source/Jobbr.Server/bin/Release/netstandard2.0/Jobbr.Server.dll source/Jobbr.Server/bin/Release/netstandard2.0/AutoMapper.dll source/Jobbr.Server/bin/Release/netstandard2.0/NCrontab.dll source/Jobbr.Server/bin/Release/netstandard2.0/Newtonsoft.Json.dll source/Jobbr.Server/bin/Release/netstandard2.0/Ninject.dll /target:library /targetplatform:v4,C:\Windows\Microsoft.NET\Framework64\v4.0.30319 /wildcards /internalize:internalize_exclude.txt /allowDup:HttpRequestMessageExtensions /allowDup:MediaTypeFormatterExtensions
  - cmd: nuget pack source\Jobbr.Server.nuspec -version "%GitVersion_SemVer%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Jobbr.Server.%GitVersion_SemVer%.nupkg"

deploy:
- provider: NuGet
  server: https://nuget.org
  api_key:
    secure: +AgExDSzPqydFKSbpQBS0j3s8d3rwTli8aRmMbUZ3DVBL29Lj7MNPOxEDLJT7f07
  on:
    appveyor_repo_tag: true
